/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess.ajedrez;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author eyehalcon97
 */
public class Tablero extends java.awt.Panel {

    /**
     * Creates new form Tablero
     */
    private JPanel[][] Casillas = new JPanel[8][8];
    public Tablero() {
        initComponents();
        iniciarjuego();
    }
    
    public void iniciarjuego(){
        for(int i=0;i<8;i++){
            for(int j=0;j<8;j++){
                Casillas[i][j] = new JPanel();
                Casillas[i][j].setMaximumSize(new java.awt.Dimension(20, 20));
                Casillas[i][j].setMinimumSize(new java.awt.Dimension(20, 20));
                Casillas[i][j].setPreferredSize(new java.awt.Dimension(20, 20));
                if(j%2 == 0){
                    Casillas[i][j].setBackground(Color.BLACK);
                }

                add(Casillas[i][j]);
                
            }
        }
        for(int i=0;i<8;i++){
            
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setLayout(new java.awt.GridLayout(8, 8));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
