/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess.Figuras;

/**
 *
 * @author eyehalcon97
 */
public abstract class Figura extends javax.swing.JPanel {

    /**
     * Creates new form Figura
     */
    protected int fila = 0;
    protected int col = 0;
    protected boolean jugador;
    public Figura() {
        initComponents();
    }
    public Figura(int fila,int col,boolean jugador){
        this.fila=fila;
        this.col = col;
        this.jugador = jugador;
    }
    
    public void setFila(int fila){
        this.fila = fila;
    }
    public void setCol(int col){
        this.col = col;
    }
    public void setJugador(boolean jugador){
        this.jugador = jugador;
    }
    public int getCol(){
        return col;
    }
    public int getFila(){
        return fila;
    }
    public boolean getJugador(){
        return jugador;
    }
    public void mover(int fila,int col){
        this.fila=fila;
        this.col=col;
    }
    public abstract boolean puedomover();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
